spring.application.name=Ders
spring.datasource.url=jdbc:postgresql://localhost:5432/Ders
spring.datasource.username=admin
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.mvc.locale=tr_TR